name: build examples

env:
  COMPONENT: tca9535

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      matrix:
        target: [esp32s3]
        esp_idf_version: [v5.4.1]
        path: ['tca9535/examples/get_started']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.esp_idf_version }}
          target: ${{ matrix.target }}
          path: ${{ matrix.path }}
          command: 'idf.py build size'

  upload_components:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: ${{ env.COMPONENT }}
          version: ${{ github.ref_name }}
          namespace: 'supcik'
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          directories: ${{ env.COMPONENT }}
